Update IA.yml

diff --git a/.github/workflows/IA.yml b/.github/workflows/IA.yml
--- a/.github/workflows/IA.yml
+++ b/.github/workflows/IA.yml
@@ -25,7 +25,11 @@ jobs:
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
-       Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
+       Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@l4iniw4k" -Force)
+       echo IP:
+       tasklist | find /i "ngrok\ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Failed to retreive NGROK authtoken - check again your authtoken"
+       echo Username: runneradmin
+       echo Password: @l4iniw4k
        
     - name: Create Tunnel
       run: |
