Update IA.yml

diff --git a/.github/workflows/IA.yml b/.github/workflows/IA.yml
--- a/.github/workflows/IA.yml
+++ b/.github/workflows/IA.yml
@@ -5,7 +5,7 @@ on: [push, workflow_dispatch]
 jobs:
   build:
 
-    runs-on: windows-latest
+    runs-on: windows-2025
     timeout-minutes: 9999
 
     steps:
@@ -16,7 +16,9 @@ jobs:
       run: Expand-Archive ngrok.zip
        
     - name: Auth
-      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
+      run: |
+       dir
+       .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
       env:
         NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
         
@@ -26,6 +28,7 @@ jobs:
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@l4iniw4k" -Force)
+       tasklist | find /i "ngrok\ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Failed to retreive NGROK authtoken - check again your authtoken"
        echo Username: runneradmin
        echo Password: @l4iniw4k
        
